name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable toolchain
        run: rustup toolchain install stable --component rustfmt --component clippy

      - name: Install nightly toolchain
        run: rustup toolchain install nightly --component rust-src --component rustfmt

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-

      - name: Install bpf-linker
        run: cargo +stable install bpf-linker

      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

      - name: Check
        run: cargo check

      - name: Clippy
        run: cargo clippy --package ebpf-xdp-program --package ebpf-xdp-program-common

      - name: Test
        run: cargo test
